name: qiandaobot-rs

networks:
  app-network:

services:
  bot:
    build:
      context: .
      dockerfile: docker/qiandaobot/Dockerfile
    networks:
      - app-network
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: qiandaobot
      POSTGRES_USER: qiandaobot
      POSTGRES_PASSWORD: qiandaobot
    ports:
      - "5432:5432"
    networks:
      - app-network
